//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveTask.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CellCode()
        {
            this.Archive = new HashSet<Archive>();
            this.InventoryNumber = new HashSet<InventoryNumber>();
        }
    
        public int Id { get; set; }
        public string CellCodeName { get; set; }
        public string Rack { get; set; }
        public string Shelf { get; set; }
        public string Cell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archive> Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryNumber> InventoryNumber { get; set; }
    }
}
