//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveTask.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryNumber()
        {
            this.Document = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string InventoryNumberName { get; set; }
        public string Theme { get; set; }
        public string Count { get; set; }
        public string DateOfReceipt { get; set; }
        public int CellCodeId { get; set; }
    
        public virtual CellCode CellCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
    }
}
