//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveTask.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchiveTask17Entities : DbContext
    {
        public ArchiveTask17Entities()
            : base("name=ArchiveTask17Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CellCode> CellCode { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Fill> Fill { get; set; }
        public virtual DbSet<InventoryNumber> InventoryNumber { get; set; }
        public virtual DbSet<IssuanceOfADocument> IssuanceOfADocument { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
